spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    oracle配置
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.73.10:1521/orcl
    username: NEWRISK
    password: NEWRISK


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 9999
